project:
  type: book
  output-dir: docs

book:
  title: "Stark Protocol"
  author: "Diego Saavedra"
  output-file: "stark-protocol"  
  date: today
  date-format: medium
  favicon: images/stark.png
  description: Uso Efectivo de Inteligencia Artificial
  keyword: AI, ChatGPT, Prompt Engineering
  url: https://github.com/statick88/curso-stark-protocol
  page-navigation: true
  sidebar: 
    logo: images/stark.png
    search: true
    collapse-level: 1

  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf]
  image: images/stark.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Contenido Teórico"
      chapters:
        - contenido/unidad1.qmd
        - contenido/unidad2.qmd
        - contenido/unidad3.qmd
        - contenido/unidad4.qmd
        - contenido/unidad5.qmd
        - contenido/unidad6.qmd
    - part: "Laboratorios"
      chapters:
        - labs/lab-unidad1.md
        - labs/lab-unidad2.md
        - labs/lab-unidad3.md
        - labs/lab-unidad4.md
        - labs/lab-unidad5.md
        - labs/lab-unidad6.md
    - part: "Evaluación"
      chapters:
        - quizzes/unidad1.md
        - quizzes/unidad2.md
        - quizzes/unidad3.md
        - quizzes/unidad4.md
        - quizzes/unidad5.md
        - quizzes/unidad6.md
    - part: "Información"
      chapters:
        - about.qmd
        - license.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    theme: solar
    number-sections: true
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
